# Generated by Django 5.0.3 on 2024-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('creation_date', models.DateTimeField()),
                ('deadline_date', models.DateTimeField()),
                ('time_left', models.DurationField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
