# Generated by Django 5.0.3 on 2024-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_left',
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
