# Generated by Django 5.0.2 on 2024-03-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_taskgroup_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
