# Generated by Django 5.0.2 on 2024-04-05 07:52

import django.db.models.deletion
import todolist.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroup',
            name='owner',
            field=models.ForeignKey(default=todolist.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='taskgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
